service: readsmart

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-2

  environment:
    BABEL_CACHE_PATH: "/tmp/babelcache"

functions:
  ProxyApiRoot:
    handler: src/server/lambda.handler
    timeout: 60
    events:
      - http:
          path: /{proxy+}
          method: ANY
